///////////////////////////////////////////////////////////////////////////
////                             usb.c                                 ////
////                                                                   ////
//// Standard USB request and token handler code.                      ////
////                                                                   ////
//// This file is part of CCS's PIC USB driver code, which includes:   ////
////   usb_desc.h - an example set of config and device descriptors    ////
////   usb.c - USB token and request handler code                      ////
////   usb.h - definitions, prototypes and global variables            ////
////   And the hardware peripheral level.  At the time of writing,     ////
////    CCS provides two hardware peripheral drivers.  National        ////
////    USBN960x (usbn960x.cc) and PIC16C7x5 (usb_pic.c).              ////
////                                                                   ////
//// When developing using this driver, files must be included in this ////
//// order:                                                            ////
////   usb.h                                                           ////
////   usb_desc.h (or your own descriptor file)                        ////
////   <hardware layer code>                                           ////
////   usb.c                                                           ////
////                                                                   ////
//// Two examples are given using CCS's PIC USB driver.                ////
//// ex_usb_scope.c is a bulk device that sends 512 bytes to the       ////
//// host and uses the USBN960x.  ex_usb_hid.c is a HID device and     ////
//// uses the PIC16C7x5.                                               ////
////                                                                   ////
//// The majority of this code is called and used by the interrupt     ////
//// generated by the hardware level, and therefore it is not meant    ////
//// to be called by the user.  The following functions are of use to  ////
//// the user (for more docs on the functions, read the comments at    ////
//// each function):                                                   ////
////                                                                   ////
////   *************************  NOTE  **************************     ////
////    This code will not create a multiple configuration device.     ////
////    If you wish to create a multiple configuration device then you ////
////    will have to modify these drivers.                             ////
////                                                                   ////
////   *************************  NOTE  **************************     ////
////   This code does not support Get_Idle, Set_Idle, Get_Protocol     ////
////   and Set_Protocol HID-specific requests.  These requests are     ////
////   optional.  If you want to support these requests you must       ////
////   provide the code yourself.  See usb_get_idle(), usb_set_idle(), ////
////   usb_get_protocol() and usb_set_protocol().                      ////
////                                                                   ////
////    **********************  FUNCTIONS  ***********************     ////
////                                                                   ////
//// usb_enumerated() - returns TRUE if device has been enumerated     ////
////                    (configured) by host, FALSE if it has not.     ////
////                    Do not try to use the USB peripheral until you ////
////                    are enumerated.                                ////
////                                                                   ////
//// usb_wait_for_enumeration() - Sits in an infinte loop until device ////
////                              is enumerated.                       ////
////                                                                   ////
//// usb_puts() - Sends a multiple packet message to the host          ////
////                                                                   ////
////                                                                   ////
//// THE FOLLOWING FUNCTIONS ARE IN-EFFECIENT, BUT PROVIDE AN EXAMPLE  ////
////  OF HOW TO GET DATA FROM THE USB CODE:                            ////
////                                                                   ////
//// usb_kbhit() - Similar to kbhit(), returns TRUE if there is new    ////
////               data in the USB RX buffers.                         ////
////                                                                   ////
//// usb_gets() - Gets data from the local USB RX buffers.             ////
////                                                                   ////
////                                                                   ////
//// The rest of the functions in this file are part of the USB        ////
//// interrupt service routine and are not meant to be called by the   ////
//// user.                                                             ////
////                                                                   ////
///////////////////////////////////////////////////////////////////////////
////                                                                   ////
//// If you wish to provide your own USB peripheral hardware layer, it ////
//// must include the following functions:                             ////
////                                                                   ////
//// void usb_stall_ep(int8 endpoint, int1 direction);                 ////
//// void usb_unstall_ep(int8 endpoint, int1 direction);               ////
//// int1 usb_endpoint_stalled(int8 endpoint, int1 direction);         ////
//// void usb_set_address(int8 address);                               ////
//// void usb_set_configured(int config);                              ////
//// int8 usb_get_packet(int8 endpoint, int8 * ptr, int8 max);         ////
//// int1 usb_put_packet(int endpoint, int * ptr, int len, PID_TOGGLE toggle); ////
//// void usb_wrongstate();                                            ////
////                                                                   ////
//// CCS provides a USB peripheral hardware layer for PIC16C765        ////
//// (pic_usb.h) and National's USBN960x (usbn960x.c).  See these      ////
//// files for more documentation.                                     ////
////                                                                   ////
///////////////////////////////////////////////////////////////////////////
////                                                                   ////
//// Version History:                                                  ////
////                                                                   ////
//// December 5th, 2003: Fixed a potential bug where descriptors are   ////
////         evenly dividable by 8 (MAX_EP0_PACKET_SIZE)               ////
////                                                                   ////
//// October 15th, 2003: Support for boot protocol added.              ////
////         Set USB_BOOT_PROTOCOL to TRUE to support this.            ////
////         The array hid_protocol[] saves which protocol mode each   ////
////         interface is in.  It is your applications job to send     ////
////         data that either fit the boot protocol or HID protocol.   ////
////                                                                   ////
//// May 6th, 2003: Fixed a potential stack overflow using PCM         ////
////                                                                   ////
//// October 28th, 2002: Problem with usb_puts and timeout fixed.      ////
////                                                                   ////
//// October 28th, 2002: Typo fixed in get_next_string_character(),    ////
////                     although it didn't cause any serious problems ////
////                                                                   ////
//// October 25th, 2002: Another change to usb_puts() was made to fix  ////
////                     problems with multiple packet messages        ////
//// October 29th, 2002: Fixed a problem with multiple packet string   ////
////                     descriptors that require a 0 len packet to    ////
////                     end message.                                  ////
////                                                                   ////
//// October 23rd, 2002: usb_puts() will bomb out of error quicker     ////
////                                                                   ////
//// August 2nd, 2002: Initial Public Release                          ////
////                                                                   ////
//// TODO: Change usb_kbhit(), usb_gets(), usb_token_reset() and       ////
////       usb_isr_tok_out_dne() to use pointers instead of multiple   ////
////       #if code #endif.                                            ////
////                                                                   ////
///////////////////////////////////////////////////////////////////////////
////        (C) Copyright 1996,2002 Custom Computer Services           ////
//// This source code may only be used by licensed users of the CCS    ////
//// C compiler.  This source code may only be distributed to other    ////
//// licensed users of the CCS C compiler.  No other use,              ////
//// reproduction or distribution is permitted without written         ////
//// permission.  Derivative programs created using this software      ////
//// in object code form are not restricted in any way.                ////
///////////////////////////////////////////////////////////////////////////

#IFNDEF __USB_DRIVER__
#DEFINE __USB_DRIVER__

#include <usb.h>

#IFNDEF __USB_HARDWARE__
   #ERROR You must include USB hardware driver.
#ENDIF

#IFNDEF __USB_DESCRIPTORS__
 #include <usb_desc.h>  //if USB descriptors haven't been included by the users, use CCS's default ones
#ENDIF

#IF USB_BOOT_PROTOCOL
int hid_protocol[USB_NUM_INTERFACES]={1};
#ENDIF

int USB_Interface[USB_NUM_INTERFACES];              //config state for all of our interfaces, NUM_INTERFACES defined with descriptors

/// BEGIN User Functions

/**************************************************************
/* usb_enumerated()
/*
/* Input: Global variable USB_Curr_Config
/* Returns: Returns a 1 if device is configured / enumerated,
/*          Returns a 0 if device is un-configured / not enumerated.
/*
/* Summary: Use this to see if device is configured / enumerated.
/***************************************************************/
int1 usb_enumerated(void) {
   if (USB_Curr_Config) {return(1);}
   else {return(0);}
}

/**************************************************************
/* usb_wait_for_enumeration()
/*
/* Input: Global variable USB_Curr_Config
/*
/* Summary: Waits in-definately until device is configured / enumerated.
/***************************************************************/
void usb_wait_for_enumeration(void) {
   while (USB_Curr_Config == 0) {restart_wdt();}
}

/****************************************************************************
/* usb_puts(endpoint, *ptr, len, packet_size, timeout)
/*
/* Inputs: endpoint - endpoint to send data out
/*         ptr - points to array of data to send
/*         len - amount of data to send
/*         packet_size - the max packet size of the endpoint
/*         timeout - time in seconds, for each packet, to wait before timeout.
/*                   set to 0 for no timeout.
/*
/* Summary: Used for sending multiple packets of data as one message.  If sending
/*          only one packet it is more effecient to use only usb_put_packet()
/*
/*****************************************************************************/
int1 usb_puts(int8 endpoint, int8 * ptr, int16 len, int8 packet_size, int8 timeout) {
   int16 i=0, tries;
   int8 seconds;
   int1 res=1;
   int8 this_packet_len;

   //send data packets until timeout or no more packets to send
   while ((i < len)&&(res)) {
      if ((len - i) > packet_size) {this_packet_len=packet_size;}
      else {this_packet_len=len-i;}
      tries=0;
      seconds=0;
      do {
         res=usb_put_packet(endpoint,ptr + i,this_packet_len,TOGGLE);   //send 64 byte packets
         delay_ms(1);
         tries++;
         if (tries==1000) {tries=0; seconds++;}
      } while ((!res)&&(seconds != timeout));
      i+=packet_size;
   }


   //send 0len packet if needed
   if ((res)&&(i==len)) {
      tries=0;
      seconds=0;
      do {
         res=usb_put_packet(endpoint,ptr,0,TOGGLE);   //indicate end of message
         delay_ms(1);
         tries++;
         if (tries==1000) {tries=0; seconds++;}
      } while ((!res)&&(seconds != timeout));
   }

   return(res);
}

/****************************************************************************
/* usb_kbhit(endpoint)
/*
/* Input: endpoint - endpoint to check
/*
/* Output: TRUE if there is new data in RX buffer, FALSE if there is not.
/*
/* Summary: Similar to kbhit(), sees if there is new data in the RX USB buffers.
/*
/*          NOTE - After getting the data, you must clear the .rx and .ov status bits.
/*
/*****************************************************************************/
int1 usb_kbhit(int8 endpoint) {
#IF USB_EP1_RX_ENABLE
   if (endpoint==1) {
      return(usb_ep1_rx_status.rx);
   }
#ENDIF

#IF USB_EP2_RX_ENABLE
   if (endpoint==2) {
      return(usb_ep2_rx_status.rx);
   }
#ENDIF

#IF USB_EP3_RX_ENABLE
   if (endpoint==3) {
      return(usb_ep3_rx_status.rx);
   }
#ENDIF

#IF USB_EP4_RX_ENABLE
   if (endpoint==4) {
      return(usb_ep4_rx_status.rx);
   }
#ENDIF

#IF USB_EP5_RX_ENABLE
   if (endpoint==5) {
      return(usb_ep5_rx_status.rx);
   }
#ENDIF

#IF USB_EP6_RX_ENABLE
   if (endpoint==6) {
      return(usb_ep6_rx_status.rx);
   }
#ENDIF

#IF USB_EP7_RX_ENABLE
   if (endpoint==7) {
      return(usb_ep7_rx_status.rx);
   }
#ENDIF

#IF USB_EP8_RX_ENABLE
   if (endpoint==8) {
      return(usb_ep8_rx_status.rx);
   }
#ENDIF

#IF USB_EP9_RX_ENABLE
   if (endpoint==9) {
      return(usb_ep9_rx_status.rx);
   }
#ENDIF

#IF USB_EP10_RX_ENABLE
   if (endpoint==10) {
      return(usb_ep10_rx_status.rx);
   }
#ENDIF

#IF USB_EP11_RX_ENABLE
   if (endpoint==11) {
      return(usb_ep11_rx_status.rx);
   }
#ENDIF

#IF USB_EP12_RX_ENABLE
   if (endpoint==12) {
      return(usb_ep12_rx_status.rx);
   }
#ENDIF

#IF USB_EP13_RX_ENABLE
   if (endpoint==13) {
      return(usb_ep13_rx_status.rx);
   }
#ENDIF

#IF USB_EP14_RX_ENABLE
   if (endpoint==14) {
      return(usb_ep14_rx_status.rx);
   }
#ENDIF

#IF USB_EP15_RX_ENABLE
   if (endpoint==15) {
      return(usb_ep15_rx_status.rx);
   }
#ENDIF
}

/****************************************************************************
/* usb_gets(endpoint,ptr, max)
/*
/* Input: endpoint - endpoint to get data from
/*        ptr - place / array to store data to
/*        max - max amount of data to get from USB and store into ptr
/*
/* Output: Amount of data returned.  It may be less than max.
/*
/* Summary: Gets data from the USB RX buffers, and stores into a user specified array.
/*
/*          NOTE - This function will wait in-definately until data has arrived.
/*                 USe usb_kbhit() to prevent being stuck in an infinite loop.
/*
/*          NOTE - THIS FUNCTION IS HORRIBLY IN-EFFECIENT, AND IS HERE ONLY TO PROVIDE
/*                 AN EXAMPLE OF WHERE AND HOW TO RECEIVE DATA.
/*                 The big reason for this is that all the data is currently
/*                 located in usb_epX_rx_buffer, where X is the endpoint.  Instead
/*                 of taking data from the usb_epX_rx_buffer[] and storing into
/*                 ptr it would be less resource hungry to just read usb_epX_rx_buffer[]
/*                 directly.  Remember, when accessing usb_epX_rx_buffer[] directly
/*                 be sure to clear usb_epX_rx_status.rx and usb_epX_rx_status.ov bits
/*                 when you are done dealing with the data in the RX buffer.
/*
/*
/*****************************************************************************/
int8 usb_gets(int8 endpoint, int8 * ptr, int8 max) {
   int8 i,len;

#IF USB_EP1_RX_ENABLE
   if (endpoint == 1) {
      while (usb_ep1_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep1_rx_status.len < max) {len=usb_ep1_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep1_rx_buffer[i];
         ptr++;
      }
      usb_ep1_rx_status.rx=0;
      usb_ep1_rx_status.ov=0;
      return(len);
   }
#ENDIF

#IF USB_EP2_RX_ENABLE
   if (endpoint == 2) {
      while (usb_ep2_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep2_rx_status.len < max) {len=usb_ep2_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep2_rx_buffer[i];
         ptr++;
      }
      usb_ep2_rx_status.rx=0;
      usb_ep2_rx_status.ov=0;
      return(len);
   }
#ENDIF

#IF USB_EP3_RX_ENABLE
   if (endpoint == 3) {
      while (usb_ep3_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep3_rx_status.len < max) {len=usb_ep3_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep3_rx_buffer[i];
         ptr++;
      }
      usb_ep3_rx_status.rx=0;
      usb_ep3_rx_status.ov=0;
      return(len);
   }
#ENDIF

#IF USB_EP4_RX_ENABLE
   if (endpoint == 4) {
      while (usb_ep4_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep4_rx_status.len < max) {len=usb_ep4_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep4_rx_buffer[i];
         ptr++;
      }
      usb_ep4_rx_status.rx=0;
      usb_ep4_rx_status.ov=0;
      return(len);
   }
#ENDIF

#IF USB_EP5_RX_ENABLE
   if (endpoint == 1) {
      while (usb_ep5_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep5_rx_status.len < max) {len=usb_ep5_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep5_rx_buffer[i];
         ptr++;
      }
      usb_ep5_rx_status.rx=0;
      usb_ep5_rx_status.ov=0;
      return(len);
   }
#ENDIF

#IF USB_EP6_RX_ENABLE
   if (endpoint == 6) {
      while (usb_ep6_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep6_rx_status.len < max) {len=usb_ep6_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep6_rx_buffer[i];
         ptr++;
      }
      usb_ep6_rx_status.rx=0;
      usb_ep6_rx_status.ov=0;
      return(len);
   }
#ENDIF

#IF USB_EP7_RX_ENABLE
   if (endpoint == 7) {
      while (usb_ep7_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep7_rx_status.len < max) {len=usb_ep7_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep7_rx_buffer[i];
         ptr++;
      }
      usb_ep7_rx_status.rx=0;
      usb_ep7_rx_status.ov=0;
      return(len);
   }
#ENDIF

#IF USB_EP8_RX_ENABLE
   if (endpoint == 8) {
      while (usb_ep8_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep8_rx_status.len < max) {len=usb_ep8_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep8_rx_buffer[i];
         ptr++;
      }
      usb_ep8_rx_status.rx=0;
      usb_ep8_rx_status.ov=0;
      return(len);
   }
#ENDIF

#IF USB_EP9_RX_ENABLE
   if (endpoint == 9) {
      while (usb_ep9_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep9_rx_status.len < max) {len=usb_ep9_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep9_rx_buffer[i];
         ptr++;
      }
      usb_ep9_rx_status.rx=0;
      usb_ep9_rx_status.ov=0;
      return(len);
   }
#ENDIF

#IF USB_EP10_RX_ENABLE
   if (endpoint == 10) {
      while (usb_ep10_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep10_rx_status.len < max) {len=usb_ep10_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep10_rx_buffer[i];
         ptr++;
      }
      usb_ep10_rx_status.rx=0;
      usb_ep10_rx_status.ov=0;
      return(len);
   }
#ENDIF

#IF USB_EP11_RX_ENABLE
   if (endpoint == 11) {
      while (usb_ep11_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep11_rx_status.len < max) {len=usb_ep11_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep11_rx_buffer[i];
         ptr++;
      }
      usb_ep11_rx_status.rx=0;
      usb_ep11_rx_status.ov=0;
      return(len);
   }
#ENDIF

#IF USB_EP12_RX_ENABLE
   if (endpoint == 12) {
      while (usb_ep12_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep12_rx_status.len < max) {len=usb_ep12_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep12_rx_buffer[i];
         ptr++;
      }
      usb_ep12_rx_status.rx=0;
      usb_ep12_rx_status.ov=0;
      return(len);
   }
#ENDIF

#IF USB_EP13_RX_ENABLE
   if (endpoint == 13) {
      while (usb_ep13_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep13_rx_status.len < max) {len=usb_ep13_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep13_rx_buffer[i];
         ptr++;
      }
      usb_ep13_rx_status.rx=0;
      usb_ep13_rx_status.ov=0;
      return(len);
   }
#ENDIF

#IF USB_EP14_RX_ENABLE
   if (endpoint == 14) {
      while (usb_ep14_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep14_rx_status.len < max) {len=usb_ep14_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep14_rx_buffer[i];
         ptr++;
      }
      usb_ep14_rx_status.rx=0;
      usb_ep14_rx_status.ov=0;
      return(len);
   }
#ENDIF

#IF USB_EP15_RX_ENABLE
   if (endpoint == 1) {
      while (usb_ep15_rx_status.rx != 1) {}   //wait until data arrives
      if (usb_ep15_rx_status.len < max) {len=usb_ep15_rx_status.len;} else {len=max;}
      for (i=0;i<len;i++) {
         *ptr=usb_ep15_rx_buffer[i];
         ptr++;
      }
      usb_ep15_rx_status.rx=0;
      usb_ep15_rx_status.ov=0;
      return(len);
   }
#ENDIF
   return(0);
}

/// END User Functions


/// BEGIN USB Token, standard and HID request handler (part of ISR)

/**************************************************************
/* usb_token_reset()
/*
/* Output: modifies global variables USB_Interface[], in[], String_ptr,
/*         String_end, USB_status_device, USB_dev_req
/*
/* Summary: Resets the token handler to initial (unconfigured) state.
/***************************************************************/
void usb_token_reset() {
   int i;

   for (i=0;i<USB_NUM_INTERFACES;i++) {
      USB_Interface[i]=0;   //reset each interface to default
      #IF USB_BOOT_PROTOCOL
       hid_protocol[i]=1;
      #endif
   }

   for (i=0;i<USB_EP0_RX_SIZE;i++) {
      usb_ep0_rx_buffer[i]=0;
   }
   usb_ep0_rx_status.rx=0;
   usb_ep0_rx_status.ov=0;


#if USB_EP1_RX_SIZE
   for (i=0;i<USB_EP1_RX_SIZE;i++) {
      usb_ep1_rx_buffer[i]=0;
   }
   usb_ep1_rx_status.rx=0;
   usb_ep1_rx_status.ov=0;
#endif

#if USB_EP2_RX_SIZE
   for (i=0;i<USB_EP2_RX_SIZE;i++) {
      usb_ep2_rx_buffer[i]=0;
   }
   usb_ep2_rx_status.rx=0;
   usb_ep2_rx_status.ov=0;
#endif

#if USB_EP3_RX_SIZE
   for (i=0;i<USB_EP3_RX_SIZE;i++) {
      usb_ep3_rx_buffer[i]=0;
   }
   usb_ep3_rx_status.rx=0;
   usb_ep3_rx_status.ov=0;
#endif

#if USB_EP4_RX_SIZE
   for (i=0;i<USB_EP4_RX_SIZE;i++) {
      usb_ep4_rx_buffer[i]=0;
   }
   usb_ep4_rx_status.rx=0;
   usb_ep4_rx_status.ov=0;
#endif

#if USB_EP5_RX_SIZE
   for (i=0;i<USB_EP5_RX_SIZE;i++) {
      usb_ep5_rx_buffer[i]=0;
   }
   usb_ep5_rx_status.rx=0;
   usb_ep5_rx_status.ov=0;
#endif

#if USB_EP6_RX_SIZE
   for (i=0;i<USB_EP6_RX_SIZE;i++) {
      usb_ep6_rx_buffer[i]=0;
   }
   usb_ep6_rx_status.rx=0;
   usb_ep6_rx_status.ov=0;
#endif

#if USB_EP7_RX_SIZE
   for (i=0;i<USB_EP7_RX_SIZE;i++) {
      usb_ep7_rx_buffer[i]=0;
   }
   usb_ep7_rx_status.rx=0;
   usb_ep7_rx_status.ov=0;
#endif

#if USB_EP8_RX_SIZE
   for (i=0;i<USB_EP8_RX_SIZE;i++) {
      usb_ep8_rx_buffer[i]=0;
   }
   usb_ep8_rx_status.rx=0;
   usb_ep8_rx_status.ov=0;
#endif

#if USB_EP9_RX_SIZE
   for (i=0;i<USB_EP9_RX_SIZE;i++) {
      usb_ep9_rx_buffer[i]=0;
   }
   usb_ep9_rx_status.rx=0;
   usb_ep9_rx_status.ov=0;
#endif

#if USB_EP10_RX_SIZE
   for (i=0;i<USB_EP10_RX_SIZE;i++) {
      usb_ep10_rx_buffer[i]=0;
   }
   usb_ep10_rx_status.rx=0;
   usb_ep10_rx_status.ov=0;
#endif

#if USB_EP11_RX_SIZE
   for (i=0;i<USB_EP11_RX_SIZE;i++) {
      usb_ep11_rx_buffer[i]=0;
   }
   usb_ep11_rx_status.rx=0;
   usb_ep11_rx_status.ov=0;
#endif

#if USB_EP12_RX_SIZE
   for (i=0;i<USB_EP12_RX_SIZE;i++) {
      usb_ep12_rx_buffer[i]=0;
   }
   usb_ep12_rx_status.rx=0;
   usb_ep12_rx_status.ov=0;
#endif

#if USB_EP13_RX_SIZE
   for (i=0;i<USB_EP13_RX_SIZE;i++) {
      usb_ep13_rx_buffer[i]=0;
   }
   usb_ep13_rx_status.rx=0;
   usb_ep13_rx_status.ov=0;
#endif

#if USB_EP14_RX_SIZE
   for (i=0;i<USB_EP14_RX_SIZE;i++) {
      usb_ep14_rx_buffer[i]=0;
   }
   usb_ep14_rx_status.rx=0;
   usb_ep14_rx_status.ov=0;
#endif

#if USB_EP15_RX_SIZE
   for (i=0;i<USB_EP15_RX_SIZE;i++) {
      usb_ep15_rx_buffer[i]=0;
   }
   usb_ep15_rx_status.rx=0;
   usb_ep15_rx_status.ov=0;
#endif

    String_ptr=0;           //used for get_descriptor
    String_end=0;           //used for get_descriptor

    USB_Curr_Config=0;      //unconfigured device

    USB_status_device=1;    //previous state.  init at none
    USB_dev_req=NONE;       //previous token request state.  init at none
}

/**************************************************************
/* usb_isr_tkn_CheckVendor()
/*
/* Input:
/* Output:
/* Returns:
/* Calls:
/*
/* Summary:
/* These functions are the responsibility of the user to write if they
/* want them as they are application dependant
/***************************************************************/
void usb_isr_tkn_CheckVendor() {
}

///---------------------------------------------------------------///
/// Processing Message stages is the biggest portion of the ISR   ///
///---------------------------------------------------------------///

/**************************************************************
/* usb_isr_tok_in_dne(endpoint)
/*
/* Input: endpoint - which endpoint we are processing a setup token.  Should be 0.
/*
/* Summary: When receiving an IN token from the PC on endpoint 0 that means the
/*          host is asking for a response from a setup token, or the next packet
/*          from a currently processing token.  (For example, a 24 byte descriptor
/*          would require 3 IN tokens if the packet size is 8 bytes.)  USB_dev_req
/*          is a global variable that defines what setup token we are currently processing.
/*
/* Part of USB interrupt service routine.
/* Only checks endpoint 0.
/***************************************************************/
void usb_isr_tok_in_dne(int8 endpoint) {
   if (endpoint==0) {
      if (USB_dev_req == GET_DESCRIPTOR) {usb_copy_config_seg_to_ep(0,TOGGLE);} //check this, we are missing report descriptor?
      else if (USB_dev_req == GET_STRING_DESCRIPTOR) {usb_copy_string_seg_to_ep(0,TOGGLE);}
      else if (USB_dev_req == GET_DEVICE) {usb_copy_device_seg_to_ep(0,TOGGLE);}
#IF USB_HID_DEVICE
      else if (USB_dev_req == GET_HID_DESC) {usb_copy_config_seg_to_ep(0,TOGGLE);}
      else if (USB_dev_req == GET_HID_REP) {usb_copy_hid_seg_to_ep(0,TOGGLE);}
#ENDIF
      else if (USB_dev_req == SET_ADDRESS) {usb_finish_set_address();}
      else if (USB_dev_req == SET_FEATURE) {usb_put_packet(0,0,0,DATA1);}
      else if (USB_dev_req == CLEAR_FEATURE) {usb_put_packet(0,0,0,DATA1);}
      else if (USB_dev_req == SET_CONFIG) {usb_put_packet(0,0,0,DATA1);}
      else if (USB_dev_req == SEND_0LEN) {usb_put_packet(0,0,0,DATA1); USB_dev_req=NONE;}
      else if (USB_dev_req == SEND_0LEN_TGL) {usb_put_packet(0,0,0,TOGGLE); USB_dev_req=NONE;}
   }
}

/**************************************************************
/* usb_isr_tok_out_dne(endpoint)
/*
/* Input: endpoint contains which endpoint we are receiving data.
/*        This code doesn't allow reception of data from EP0. (Add later)
/*
/* Summary: Processes out tokens (out is respective of the host, so actualy incoming
/*          to the pic), but not out setup tokens.  Data is placed into a
/*          a buffer if it is empty, and the rx flag is set.  If the buffer
/*          is not empty then the overrun bit of that EP status byte is set it.
/***************************************************************/
void usb_isr_tok_out_dne(int8 endpoint) {
#if USB_EP1_RX_SIZE
   if (endpoint == 1) {

      usb_ep1_rx_status.len=usb_get_packet(endpoint,usb_ep1_rx_buffer,USB_EP1_RX_SIZE);
      if (usb_ep1_rx_status.rx == 1) {
         usb_ep1_rx_status.ov = 1;
      }
      usb_ep1_rx_status.rx = 1;
   }
#endif
#if USB_EP2_RX_SIZE
   if (endpoint == 2) {

      usb_ep2_rx_status.len=usb_get_packet(endpoint,usb_ep2_rx_buffer,USB_EP2_RX_SIZE);
      if (usb_ep2_rx_status.rx == 1) {
         usb_ep2_rx_status.ov = 1;
      }
      usb_ep2_rx_status.rx = 1;
   }
#endif
#if USB_EP3_RX_SIZE
   if (endpoint == 3) {

      usb_ep3_rx_status.len=usb_get_packet(endpoint,usb_ep3_rx_buffer,USB_EP3_RX_SIZE);
      if (usb_ep3_rx_status.rx == 1) {
         usb_ep3_rx_status.ov = 1;
      }
      usb_ep3_rx_status.rx = 1;
   }
#endif
#if USB_EP4_RX_SIZE
   if (endpoint == 4) {

      usb_ep4_rx_status.len=usb_get_packet(endpoint,usb_ep4_rx_buffer,USB_EP4_RX_SIZE);
      if (usb_ep4_rx_status.rx == 1) {
         usb_ep4_rx_status.ov = 1;
      }
      usb_ep4_rx_status.rx = 1;
   }
#endif
#if USB_EP5_RX_SIZE
   if (endpoint == 5) {

      usb_ep5_rx_status.len=usb_get_packet(endpoint,usb_ep5_rx_buffer,USB_EP5_RX_SIZE);
      if (usb_ep5_rx_status.rx == 1) {
         usb_ep5_rx_status.ov = 1;
      }
      usb_ep5_rx_status.rx = 1;
   }
#endif
#if USB_EP6_RX_SIZE
   if (endpoint == 6) {

      usb_ep6_rx_status.len=usb_get_packet(endpoint,usb_ep6_rx_buffer,USB_EP6_RX_SIZE);
      if (usb_ep6_rx_status.rx == 1) {
         usb_ep6_rx_status.ov = 1;
      }
      usb_ep6_rx_status.rx = 1;
   }
#endif
#if USB_EP7_RX_SIZE
   if (endpoint == 7) {

      usb_ep7_rx_status.len=usb_get_packet(endpoint,usb_ep7_rx_buffer,USB_EP7_RX_SIZE);
      if (usb_ep7_rx_status.rx == 1) {
         usb_ep7_rx_status.ov = 1;
      }
      usb_ep7_rx_status.rx = 1;
   }
#endif
#if USB_EP8_RX_SIZE
   if (endpoint == 8) {

      usb_ep8_rx_status.len=usb_get_packet(endpoint,usb_ep8_rx_buffer,USB_EP8_RX_SIZE);
      if (usb_ep8_rx_status.rx == 1) {
         usb_ep8_rx_status.ov = 1;
      }
      usb_ep8_rx_status.rx = 1;
   }
#endif
#if USB_EP9_RX_SIZE
   if (endpoint == 9) {

      usb_ep9_rx_status.len=usb_get_packet(endpoint,usb_ep9_rx_buffer,USB_EP9_RX_SIZE);
      if (usb_ep9_rx_status.rx == 1) {
         usb_ep9_rx_status.ov = 1;
      }
      usb_ep9_rx_status.rx = 1;
   }
#endif
#if USB_EP10_RX_SIZE
   if (endpoint == 10) {

      usb_ep10_rx_status.len=usb_get_packet(endpoint,usb_ep10_rx_buffer,USB_EP10_RX_SIZE);
      if (usb_ep10_rx_status.rx == 1) {
         usb_ep10_rx_status.ov = 1;
      }
      usb_ep10_rx_status.rx = 1;
   }
#endif
#if USB_EP11_RX_SIZE
   if (endpoint == 11) {

      usb_ep11_rx_status.len=usb_get_packet(endpoint,usb_ep11_rx_buffer,USB_EP11_RX_SIZE);
      if (usb_ep11_rx_status.rx == 1) {
         usb_ep11_rx_status.ov = 1;
      }
      usb_ep11_rx_status.rx = 1;
   }
#endif
#if USB_EP12_RX_SIZE
   if (endpoint == 12) {

      usb_ep12_rx_status.len=usb_get_packet(endpoint,usb_ep12_rx_buffer,USB_EP12_RX_SIZE);
      if (usb_ep12_rx_status.rx == 1) {
         usb_ep12_rx_status.ov = 1;
      }
      usb_ep12_rx_status.rx = 1;
   }
#endif
#if USB_EP13_RX_SIZE
   if (endpoint == 13) {

      usb_ep13_rx_status.len=usb_get_packet(endpoint,usb_ep13_rx_buffer,USB_EP13_RX_SIZE);
      if (usb_ep13_rx_status.rx == 1) {
         usb_ep13_rx_status.ov = 1;
      }
      usb_ep13_rx_status.rx = 1;
   }
#endif
#if USB_EP14_RX_SIZE
   if (endpoint == 14) {

      usb_ep14_rx_status.len=usb_get_packet(endpoint,usb_ep14_rx_buffer,USB_EP14_RX_SIZE);
      if (usb_ep14_rx_status.rx == 1) {
         usb_ep14_rx_status.ov = 1;
      }
      usb_ep14_rx_status.rx = 1;
   }
#endif
#if USB_EP15_RX_SIZE
   if (endpoint == 15) {

      usb_ep15_rx_status.len=usb_get_packet(endpoint,usb_ep15_rx_buffer,USB_EP15_RX_SIZE);
      if (usb_ep15_rx_status.rx == 1) {
         usb_ep15_rx_status.ov = 1;
      }
      usb_ep15_rx_status.rx = 1;
   }
#endif
}


//---- process setup message stage -----------//
////// HUGE - most of our code is to read setup messages ////

/**************************************************************
/* usb_isr_tok_setup_dne()
/*
/* Input: usb_ep0_rx_buffer[] contains the 8 bytes of the setup packet.
/*
/* Summary: This function is the start of code that handles the setup token.
/*          We must handle all relevant requests, such as Set_Configuration, Get_Descriptor, etc.
/*
/* Note: The setup packet has this configuration:
/*  usb_ep0_rx_buffer[8] now contains setup data packet, which has the following records
/*  usb_ep0_rx_buffer[0]=bmRequestType; bit7 defines (0) host-to-device or (1) device-to-host
/*                           bit6-5 (00) usb standard request; (01) class request; (10) vendor request
/*                           bit4-0 requested directed to (0000) device; (0001) interface; (0010) endpoint; (0011) other element
/*  usb_ep0_rx_buffer[1]=bRequest ; the request
/*  usb_ep0_rx_buffer[2,3]=wValue ; a value which corresponds to request
/*  usb_ep0_rx_buffer[4,5]=wIndex ; could correspond to interface or endpoint...
/*  usb_ep0_rx_buffer[6,7]=wLength ; number of bytes in next data packet
/*                        for host-to-device, this exactly how many bytes in data packet
/*                        for device-to-host, this is the maximum bytes that can fit one packet
/***************************************************************/
void usb_isr_tok_setup_dne() {
   debug(debug_txb, "S ");
   if (usb_ep0_rx_buffer[7]>0) {host_max_length=0xFF;} else {host_max_length=usb_ep0_rx_buffer[6];} //the max length the host told us we can send, no more. we can send less

   USB_dev_req=NONE; // clear the device request..

  // if (usb_ep0_rx_buffer[0] == 0x00) {usb_isr_tkn_HostToDevice();}
   if (usb_ep0_rx_buffer[0] == 0x01) {usb_isr_tkn_HostToInterface();}
   else if (usb_ep0_rx_buffer[0] == 0x02) {usb_isr_tkn_HostToEndpoint();}
   else if (usb_ep0_rx_buffer[0] == 0x80) {usb_isr_tkn_DeviceToHost();}
   else if (usb_ep0_rx_buffer[0] == 0x81) {usb_isr_tkn_InterfaceToHost();}
   else if (usb_ep0_rx_buffer[0] == 0x82) {usb_isr_tkn_EndpointToHost();}
#IF USB_HID_DEVICE
   else if ((usb_ep0_rx_buffer[0] & 0x60) == 0x20) {usb_isr_tkn_ClassRequest();}
#ENDIF
   else if ((usb_ep0_rx_buffer[0] & 0x60) == 0x40) {usb_isr_tkn_CheckVendor();}
   else {usb_isr_tkn_HostToDevice();}//cuz he gave CheckForStandardRequest and HostToDevice the same label
}

/**************************************************************
/* usb_isr_tkn_HostToDevice()
/*
/* Input: usb_ep0_rx_buffer[1] == bRequest
/*
/* Summary: bmRequestType told us it was a Host to Device request.
/*          bRequest says which request.  Only certain requests are valid,
/*          if a non-valid request was made then return with an Wrong-Statue (IDLE)
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_isr_tkn_HostToDevice() {
   if (usb_ep0_rx_buffer[1]==0x01) {usb_Clear_Device_Feature();}
   else if (usb_ep0_rx_buffer[1]==0x05) {usb_Set_Address_Token();}
   else if (usb_ep0_rx_buffer[1]==0x09) {usb_Set_Configuration_Token();}
   else if (usb_ep0_rx_buffer[1]==0x03) {usb_Set_Feature();}
   else {usb_wrongstate();}
}

/**************************************************************
/* usb_isr_tkn_HostToInterface()
/*
/* Input: usb_ep0_rx_buffer[1] == bRequest
/*
/* Summary: bmRequestType told us it was a Host to Interface request.
/*          bRequest says which request.  Only certain requests are valid,
/*          if a non-valid request was made then return with an Wrong-Statue (IDLE)
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_isr_tkn_HostToInterface() {
   if (usb_ep0_rx_buffer[1]==0x01) {usb_Clear_Interface_Feature();}
   else if (usb_ep0_rx_buffer[1]==0x0B) {usb_Set_Interface();}
   else if (usb_ep0_rx_buffer[1]==0x03) {usb_Set_Interface_Feature();}
   else {usb_wrongstate();}
}

/**************************************************************
/* usb_isr_tkn_HostToEndpoint()
/*
/* Input: usb_ep0_rx_buffer[1] == bRequest
/*
/* Summary: bmRequestType told us it was a Host to Endpoint request.
/*          bRequest says which request.  Only certain requests are valid,
/*          if a non-valid request was made then return with an Wrong-Statue (IDLE)
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_isr_tkn_HostToEndpoint() {
   if (usb_ep0_rx_buffer[1]==0x01) {usb_Clear_Endpoint_Feature();}
   else if (usb_ep0_rx_buffer[1]==0x03) {usb_Set_Endpoint_Feature();}
   else {usb_wrongstate();}
}

/**************************************************************
/* usb_isr_tkn_DeviceToHost()
/*
/* Input: usb_ep0_rx_buffer[1] == bRequest
/*
/* Summary: bmRequestType told us it was a Device to Host request.
/*          bRequest says which request.  Only certain requests are valid,
/*          if a non-valid request was made then return with an Wrong-Statue (IDLE)
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_isr_tkn_DeviceToHost() {
   if (usb_ep0_rx_buffer[1]==0x08) {usb_Get_Configuration_Token();}
   else if (usb_ep0_rx_buffer[1]==0x06) {usb_Get_Descriptor();}
   else if (usb_ep0_rx_buffer[1]==0x00) {usb_Get_Device_Status();}
   else {usb_wrongstate();}
}

/**************************************************************
/* usb_isr_tkn_InterfaceToHost()
/*
/* Input: usb_ep0_rx_buffer[1] == bRequest
/*
/* Summary: bmRequestType told us it was a Interface to Host request.
/*          bRequest says which request.  Only certain requests are valid,
/*          if a non-valid request was made then return with an Wrong-Statue (IDLE)
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_isr_tkn_InterfaceToHost() {
   if (usb_ep0_rx_buffer[1]==0x0A) {usb_Get_Interface();}
   else if (usb_ep0_rx_buffer[1]==0x00) {usb_Get_Interface_Status();}
   else if (usb_ep0_rx_buffer[1]==0x06) {usb_Get_Descriptor();}
   else {usb_wrongstate();}
}

/**************************************************************
/* usb_isr_tkn_EndpointToHost()
/*
/* Input: usb_ep0_rx_buffer[1] == bRequest
/*
/* Summary: bmRequestType told us it was a Endpoint to Host request.
/*          bRequest says which request.  Only certain requests are valid,
/*          if a non-valid request was made then return with an Wrong-Statue (IDLE)
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_isr_tkn_EndpointToHost() {
   if (usb_ep0_rx_buffer[1]==0x00) {usb_Get_Endpoint_Status();}
   else {usb_wrongstate();}
}

/**************************************************************
/* usb_isr_tkn_ClassRequest()
/*
/* Input: usb_ep0_rx_buffer[1] == bRequest
/*
/* Summary: bmRequestType told us it was a Class request.
/*          bRequest says which request.  Only certain requests are valid,
/*          if a non-valid request was made then return with an Wrong-Statue (IDLE)
/*
/*          Class requests are for HID devices.
/*
/* Part of usb_isr_tok_setup_dne()
/* Only compiled if HID_DEVICE is TRUE
/***************************************************************/
#IF USB_HID_DEVICE
void usb_isr_tkn_ClassRequest() {
	int request;

	request=usb_ep0_rx_buffer[1];

   if (request==0x09) {usb_isr_tok_out_dne(0);}
   else if (request==0x0A) {usb_set_idle();}
   else if (request==0x02) {usb_get_idle();}
   else if (request==0x0B) {usb_set_protocol();}
   else if (request==0x03) {usb_get_protocol();}

   else {usb_wrongstate();}
}


/**************************************************************
/* usb_set_idle()
/*
/* Summary: Handles Set_Idle HID request.  This request is optional.
/*          This code is not provided by CCS.
/*
/* Part of usb_isr_tok_setup_dne()
/* Only compiled if HID_DEVICE is TRUE
/***************************************************************/
void usb_set_idle(void) {
   debug(debug_txb,"SI ");
   #IF USB_SUPPORT_IDLE
      //TODO: idle code
      //id=buffer[2]
      //count=buffer[3]
      //interface=buffer[4]
   #ELSE
      usb_wrongstate();
   #ENDIF
}

/**************************************************************
/* usb_get_idle()
/*
/* Summary: Handles Get_Idle HID request.  This request is optional.
/*          This code is not provided by CCS.
/*
/* Part of usb_isr_tok_setup_dne()
/* Only compiled if HID_DEVICE is TRUE
/***************************************************************/
void usb_get_idle(void) {
   debug(debug_txb,"GI ");
   #IF USB_SUPPORT_IDLE
      //TODO: idle code
      //id=buffer[2]
   #ELSE
      usb_wrongstate();
   #ENDIF
}


/**************************************************************
/* usb_set_protocol()
/*
/* Summary: Handles Set_Protocol HID request.  This request is optional.
/*          This code is not provided by CCS.
/*
/* Part of usb_isr_tok_setup_dne()
/* Only compiled if HID_DEVICE is TRUE
/***************************************************************/
void usb_set_protocol(void) {
   debug(debug_txb,"SP ");
   #IF USB_BOOT_PROTOCOL
      hid_protocol[usb_ep0_rx_buffer[4]]=usb_ep0_rx_buffer[2];
      usb_put_packet(0,usb_ep0_rx_buffer,0,DATA1); //send 0len packet
   #ELSE
      usb_wrongstate();
   #ENDIF
}

/**************************************************************
/* usb_get_protocol()
/*
/* Summary: Handles Get_Protocol HID request.  This request is optional.
/*          This code is not provided by CCS.
/*
/* Part of usb_isr_tok_setup_dne()
/* Only compiled if HID_DEVICE is TRUE
/***************************************************************/
void usb_get_protocol(void) {
   int8 interface;

   debug(debug_txb,"GP ");

   #IF USB_BOOT_PROTOCOL
      interface=usb_ep0_rx_buffer[4];
      usb_ep0_rx_buffer[0]=hid_protocol[interface];
      usb_put_packet(0,usb_ep0_rx_buffer,1,DATA1);
   #ELSE
      usb_wrongstate();
   #ENDIF
}
#ENDIF

/**************************************************************
/* usb_Get_Descriptor()
/*
/* Input: usb_ep0_rx_buffer[3] == wValue, which descriptor we want
/*
/* Summary: Checks to see if we want a standard descriptor (Interface, Endpoint, Config, Device, String, etc.),
/*          or a class specific (HID) descriptor.
/*
/* Part of usb_isr_tok_setup_dne()
/* Part of Get_Descriptor request handler.
/***************************************************************/
void usb_Get_Descriptor() {
   if ( bit_test(usb_ep0_rx_buffer[3],5) )//	btfss	BufferData+(wValue+1),5	; get descriptor type
      {usb_GetClassSpecificDescriptor();}
   else
      {usb_GetCh9Descriptor();}
}

/**************************************************************
/* usb_GetClassSpecificDescriptor()
/*
/* Input: usb_ep0_rx_buffer[3] == wValue, which descriptor we want
/*
/* Summary: Host asked for HID descriptor, wValue tells us if they want Descriptor or Report.
/*          Only relevant if HID_DEVICE is defined as TRUE, else we return a Wrong-state (IDLE)
/*
/* Note:  This code assumes that you only have 1 class desc/report, so it doesn't look at the index.
/*
/* Part of usb_isr_tok_setup_dne()
/* Part of Get_Descriptor request handler.
/***************************************************************/
void usb_GetClassSpecificDescriptor() {
#IF USB_HID_DEVICE
   if (usb_ep0_rx_buffer[3]==0x21) {usb_Get_HID_Descriptor();}
   else if (usb_ep0_rx_buffer[3]==0x22) {usb_Get_HID_Report();}
   else {usb_wrongstate();}
#ELSE
   usb_wrongstate();
#ENDIF
}

#IF USB_HID_DEVICE
/**************************************************************
/* usb_Get_HID_Descriptor()
/*
/* Output: USB_dev_req is changed to keep status of what request we are currently processing.
/*
/* Summary: Defines the beginning (String_ptr) and the end (String_end) of the descriptor
/*          located in the CONFIG[] descriptor, and sends out the first packet containing the
/*          first few bytes of the descriptor.  The remaining bytes are sent after IN tokens.
/*
/* Part of usb_isr_tok_setup_dne()
/* Code compiled only if HID_DEVICE is defined as TRUE
/* Part of Get_Descriptor request handler.
/***************************************************************/
void usb_Get_HID_Descriptor() {
   debug(debug_txb,"DH ");
   USB_dev_req=GET_HID_DESC;
   String_ptr=USB_CLASS_DESCRIPTORS[0];
   String_end=String_ptr+USB_CONFIG_DESC[String_ptr];
   usb_copy_config_seg_to_ep(0,DATA1);
}

/**************************************************************
/* usb_Get_HID_Report()
/*
/* Output: USB_dev_req is changed to keep status of what request we are currently processing.
/*
/* Summary: Defines the beginning (String_ptr) of the HID report and sends out the
/*          first packet containing the first few bytes of the report.  The remaining bytes
/*          are sent after IN tokens.
/*
/* Part of usb_isr_tok_setup_dne()
/* Code compiled only if HID_DEVICE is defined as TRUE
/* Part of Get_Descriptor request handler.
/***************************************************************/
void usb_Get_HID_Report() {
   debug(debug_txb,"HR ");
   USB_dev_req=GET_HID_REP;  //currently processing a get descriptor request
   String_ptr=0;
   usb_copy_hid_seg_to_ep(0,DATA1);
}
#ENDIF

/**************************************************************
/* usb_GetCh9Descriptor()
/*
/* Input: usb_ep0_rx_buffer[3] == wValue, which descriptor we want
/*
/* Summary: Checks to see if which standard descriptor we wanted (Interface, Endpoint, Config, Device, or String).
/*
/* Part of usb_isr_tok_setup_dne()
/* Part of Get_Descriptor request handler.
/***************************************************************/
void usb_GetCh9Descriptor() {
   int type;

   type=usb_ep0_rx_buffer[3] & 0x03;
   if (type==USB_DEVICE_DESC_KEY) {usb_Get_Device_Descriptor();}
   else if ( (type==USB_CONFIG_DESC_KEY) || (type==USB_INTERFACE_DESC_KEY) || (type==USB_ENDPOINT_DESC_KEY) ) {usb_Get_Config_Descriptor(type);}
   else if (type==USB_STRING_DESC_KEY) {usb_Get_String_Descriptor();}

   else {usb_wrongstate();}
}

/**************************************************************
/* usb_Get_Device_Descriptor()
/*
/* Output: USB_dev_req is changed to keep status of what request we are currently processing.
/*
/* Summary: Defines the beginning (String_ptr) of the Device descriptor and sends out the
/*          first packet containing the first few bytes of the Device descriptor (located in device[]).
/*          The remaining bytes are sent after IN tokens.
/*
/* Part of usb_isr_tok_setup_dne()
/* Part of Get_Descriptor request handler.
/***************************************************************/
void usb_Get_Device_Descriptor() {
   debug(debug_txb,"DD ");

   USB_dev_req=GET_DEVICE;  //currently processing a get descriptor request

   String_ptr=0;

   usb_copy_device_seg_to_ep(0,DATA1);
}

/**************************************************************
/* usb_Get_Config_Descriptor(type)
/*
/* Input:  type = which descriptor to send
/*         usb_ep0_rx_buffer[2] == which index if multiple interfaces, configs, endpoints, etc.
/* Output: USB_dev_req is changed to keep status of what request we are currently processing.
/*
/* Summary: Defines the beginning (String_ptr) and end (String_end) of the specified config descriptor and sends out the
/*          first packet containing the first few bytes of the config descriptor (located in config[]).
/*          The remaining bytes are sent after IN tokens. Since config[] contains each config descriptor and
/*          multiple indexes String_ptr and String_end must specify the beginning and end correctly.
/*
/* Part of usb_isr_tok_setup_dne()
/* Part of Get_Descriptor request handler.
/***************************************************************/
void usb_Get_Config_Descriptor(int type) {
   int index;

   debug(debug_txb,"DC");

   USB_dev_req=GET_DESCRIPTOR; //currently processing a get descriptor request

   index=usb_ep0_rx_buffer[2];

   if (type==USB_CONFIG_DESC_KEY) { //windows hosts will send a FF max len and expect you to send all configs without asking for them individually.
      debug_txb('C');
      String_ptr=0;
      if (host_max_length > USB_TOTAL_CONFIG_LEN) {host_max_length=USB_TOTAL_CONFIG_LEN;}
      String_end=host_max_length;
   }
   //i've never seen windows ask for these two requests, but here they are anyways
   //therefore these haven't been tested by CCS.
   else if (type==USB_INTERFACE_DESC_KEY) {debug_txb('I'); String_ptr=USB_INTERFACE_DESCRIPTORS[index]; String_end=String_ptr+USB_CONFIG_DESC[String_ptr];}
   else if (type==USB_ENDPOINT_DESC_KEY) {debug_txb('E'); String_ptr=USB_ENDPOINT_DESCRIPTORS[index]; String_end=String_ptr+USB_CONFIG_DESC[String_ptr];}

   debug_txb(' ');

   usb_copy_config_seg_to_ep(0,DATA1);
}

/**************************************************************
/* usb_Get_String_Descriptor()
/*
/* Input:  usb_ep0_rx_buffer[2] == which index if multiple interfaces, configs, endpoints, etc.
/* Output: USB_dev_req is changed to keep status of what request we are currently processing.
/*
/* Summary: Defines the asked string (string) and end (String_end) of the specified string descriptor and sends out the
/*          first packet containing the first few bytes of the string descriptor (located in STRINGx[]).
/*          The remaining bytes are sent after IN tokens.
/*
/* Part of usb_isr_tok_setup_dne()
/* Part of Get_Descriptor request handler.
/***************************************************************/
void usb_Get_String_Descriptor() {
   debug(debug_txb,"DS ");

   USB_dev_req=GET_STRING_DESCRIPTOR;

   string=usb_ep0_rx_buffer[2];    //find string index to look up

   String_ptr=0;

   usb_copy_string_seg_to_ep(0,DATA1);
}


/**************************************************************
/* usb_Get_Device_Status()
/*
/* Output: Status is put into usb_ep0_rx_buffer[], and usb_ep0_rx_buffer[] is sent to host.
/*
/* Summary: Handles Get_Status request where recipient is device.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Get_Device_Status() {
   debug(debug_txb,"GDS ");

   usb_ep0_rx_buffer[0]=USB_status_device;
   usb_ep0_rx_buffer[1]=0;

   usb_put_packet(0,usb_ep0_rx_buffer,2,DATA1);
}

/**************************************************************
/* usb_Get_Interface_Status()
/*
/* Summary: Handles Get_Status request where recipient is interface.
/*          A do nothing response.  Always returns a two byte record, with all bits zero.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Get_Interface_Status() {
   debug(debug_txb,"GIS ");

   usb_ep0_rx_buffer[0]=0;
   usb_ep0_rx_buffer[1]=0;

   usb_put_packet(0,usb_ep0_rx_buffer,2,DATA1);
}

/**************************************************************
/* usb_Get_Endpoint_Status()
/*
/* Input: usb_ep0_rx_buffer[4] == wIndex, endpoint direction bit.
/* Output: Stall status put into usb_ep0_rx_buffer[], usb_ep0_rx_buffer sent to host.
/*
/* Summary: Handles Get_Status request where recipient is endpoint.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Get_Endpoint_Status() {
   int8 endpoint;
   int1 direction=0;

   debug(debug_txb,"GES ");

   if (bit_test(usb_ep0_rx_buffer[4],7)) {direction=1;}    //direction = 0 == OUT or CONTROL; direction = 1 == IN;
   endpoint=usb_ep0_rx_buffer[4] & 0x0F;
   usb_ep0_rx_buffer[0]=0;
   usb_ep0_rx_buffer[1]=0;

   if (endpoint < USB_MAX_ENDPOINTS) {
      if (usb_endpoint_stalled(endpoint,direction)) {
         usb_ep0_rx_buffer[0]=1;
      }
      usb_put_packet(0,usb_ep0_rx_buffer,2,DATA1);
   }
   else {usb_wrongstate();}
}

/**************************************************************
/* usb_Set_Address_Token()
/*
/* Input: usb_ep0_rx_buffer[2] == wValue, new device address
/* Output: 0 len buffer sent back to host.
/*
/* Summary: Set_Address handler.  National part handles this differently then PIC16C7x5.
/* Note: Firmware must respond within a few milli-seconds.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Set_Address_Token() {
   debug(debug_txb,"SA ");

   USB_dev_req=SET_ADDRESS; //currently processing set_address request
   USB_address_pending=usb_ep0_rx_buffer[2];


   #ifdef __USBN__
   USB_dev_req=NONE; //currently processing set_address request
   usb_set_address(USB_address_pending);
	USB_Curr_Config=0;	// make sure current configuration is 0
//   if (USB_address_pending) {usb_set_enumerated(1);} else {usb_set_enumerated(0);}
   #endif

   usb_put_packet(0,usb_ep0_rx_buffer,0,DATA1);  //send 0len packet
}

/**************************************************************
/* usb_finish_set_address()
/*
/* Input: USB_address_pending holds the address we were asked to set to.
/*
/* Summary: Sets the address.
/*
/* This code should only be run on the PIC16C7x5, and not the National part.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
 void usb_finish_set_address() {
   debug(debug_txb,"FSA ");
	USB_Curr_Config=0;	// make sure current configuration is 0

   #ifdef __PIC__
	USB_dev_req=NONE;  // no request pending
   usb_set_address(USB_address_pending);
   #endif
}

/**************************************************************
/* usb_Clear_Device_Feature()
/*
/* Input: usb_ep0_rx_buffer[2] == wValue, feature to clear
/* Output: 0 len packet sent back to host.
/*
/* Summary: Handles the Clear_Feature request where the recipient is Device.  Only
/*          feature valid for device is remote wakeup.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Clear_Device_Feature() {
   debug(debug_txb,"CDF ");
   if (usb_ep0_rx_buffer[2] == 1) {
      bit_clear(USB_status_device,1); //set device remote wakeup
      usb_put_packet(0,usb_ep0_rx_buffer,0,DATA1); //send 0len packet
   }
   else {usb_wrongstate();}
}

/**************************************************************
/* usb_Clear_Endpoint_Feature()
/*
/* Input: usb_ep0_rx_buffer[2] == wValue, feature to clear
/*        usb_ep0_rx_buffer[4] == wIndex, direction of endpoint.
/* Output: 0 len packet sent back to host.
/*
/* Summary: Handles the Clear_Feature request where the recipient is endpoint.
/*          Only endpoint feature is Endpoint halt.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Clear_Endpoint_Feature() {
   int endpoint;
   int1 direction=0;

   debug(debug_txb,"CEF ");

   if (bit_test(usb_ep0_rx_buffer[4],7)) {direction=1;}
   endpoint=usb_ep0_rx_buffer[4] & 0x0F;

   if (endpoint  < USB_MAX_ENDPOINTS) {
      usb_unstall_ep(endpoint,direction);
      usb_put_packet(0,usb_ep0_rx_buffer,0,DATA1);
   }
   else {usb_wrongstate();}
}

/**************************************************************
/* usb_Clear_Interface_Feature()
/*
/* Summary: Handles the Clear_Feature request where the recipient is interface.
/*          This is a valid request, but there are no valid features on the interface in 1.1.  Don't do anything.
/*          (Should we send a Wrong-State (IDLE))?
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Clear_Interface_Feature() {
   debug(debug_txb,"CIF ");
}

/**************************************************************
/* usb_Set_Device_Feature()
/*
/* Input:  usb_ep0_rx_buffer[2] == wValue, feature to set.
/* Output: 0 len packet sent to host.
/*
/* Summary: Set_Feature request handler where recipient is device.
/*          Only feature valid for device feature is Device Remote wakeup.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Set_Device_Feature() {
   debug(debug_txb,"SDF ");

   if (usb_ep0_rx_buffer[2]==1) {
      bit_set(USB_status_device,1);
      usb_put_packet(0,usb_ep0_rx_buffer,0,DATA1);
   }
   else {usb_wrongstate();}
}

/**************************************************************
/* usb_Set_Feature()
/*
/* Input:  usb_ep0_rx_buffer[2] == wValue, feature to set.
/* Output: 0 len packet sent to host.
/*
/* Summary: Set_Feature request handler where recipient is device.
/*          Only feature valid for device feature is Device Remote wakeup.
/*
/*          WHY DOES THIS LOOK LIKE usb_Set_Device_Feature()???
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Set_Feature() {
   debug(debug_txb,"SF ");
   if (usb_ep0_rx_buffer[2]==1) {
      bit_set(USB_status_device,1); //set device remote wakeup
      usb_put_packet(0,usb_ep0_rx_buffer,0,DATA1); //prepare 0len packet
   }
   else {usb_wrongstate();}
}

/**************************************************************
/* usb_Set_Endpoint_Feature()
/*
/* Input:  usb_ep0_rx_buffer[2] == wValue, feature to set.
/*         usb_ep0_rx_buffer[4] == wIndex, direction of endpoint
/* Output: 0 len packet sent to host.
/*
/* Summary: Set_Feature request handler where recipient is endpoint.
/*          Only endpoint feature is Endpoint halt.  This function will halt
/*          the endpoint that is requested.  The endpoint will remain halted until a reset or
/*          a Clear_Feature on the endpoint.  When the endpoint is halted it will not send or receive data.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Set_Endpoint_Feature() {
   int endpoint;
   int1 direction=0;
   debug(debug_txb,"SEF ");

   if (bit_test(usb_ep0_rx_buffer[4],7)) {direction=1;}
   endpoint=usb_ep0_rx_buffer[4] & 0x0F;

   if (endpoint != 0) { //should we let them stall ep0?  don't think so
      if (endpoint < USB_MAX_ENDPOINTS) {
         usb_stall_ep(endpoint,direction);
         usb_put_packet(0,usb_ep0_rx_buffer,0,DATA1);
      }
      else {usb_wrongstate();}
   }
}

/**************************************************************
/* usb_Set_Interface_Feature()
/*
/* Output: Since this is an invalid request, we wend a Wrong-State (IDLE) to host.
/*
/* Summary: Handles the Set_Feature request where the recipient is interface.
/*          There are no valid features on the interface in 1.1.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Set_Interface_Feature() {
   debug(debug_txb,"SIF ");
   usb_wrongstate(); //invalid request
}

/**************************************************************
/* usb_Get_Configuration_Token()
/*
/* Output: Current configuration in use is put into usb_ep0_rx_buffer[] and sent to host.
/*
/* Summary: Get_Configuration handler.  Host asks us what configuration we are using, and we respond
/*          indicating the configuration in use:
/*             Default State    - undefined
/*             Addressed State  - returns 0
/*             Configured state - returns current configured state.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Get_Configuration_Token() {
   debug(debug_txb,"GC ");
   usb_ep0_rx_buffer[0]=USB_Curr_Config;
   usb_put_packet(0,usb_ep0_rx_buffer,1,DATA1);
}

/**************************************************************
/* usb_Set_Configuration_Token()
/*
/* Input: usb_ep0_rx_buffer[2] == wValue, configuration to set to.
/* Output: if a valid configuration, we send a 0 len packet.  If invalid, we send a wrong-state (IDLE).
/*
/* Summary: Set_Configuration handler.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Set_Configuration_Token() {
   debug(debug_txb,"SC ");

   if (usb_ep0_rx_buffer[2] > USB_NUM_CONFIGURATIONS) {
      usb_wrongstate();
   }
   else {  // if config <= num configs, request appears valid
      usb_set_configured(usb_ep0_rx_buffer[2]);
      usb_put_packet(0,usb_ep0_rx_buffer,0,DATA1);; //send 0len packet
   }
}

/**************************************************************
/* usb_Get_Interface()
/*
/* Input: usb_ep0_rx_buffer[4] == wIndex, interface to get
/* Output: The current interface number.
/*
/* Summary: Get_Interface request handler.  For devices with configurations that include multiple interfaces,
/*          the host requests the current interface number.  Only valid if device is configured.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Get_Interface() {
   int interface;
   debug(debug_txb,"GI ");

   interface=usb_ep0_rx_buffer[4];

   if ( (USB_Curr_Config) && (interface < USB_NUM_INTERFACES) ) {   //book says only supports configed state
      usb_ep0_rx_buffer[0]=USB_Interface[interface];//our new outgoing byte
      usb_put_packet(0,usb_ep0_rx_buffer,1,DATA1);; //send byte back
   }
   else {
      usb_wrongstate();
   }
}

/**************************************************************
/* usb_Set_Interface()
/*
/* Input: usb_ep0_rx_buffer[2] == wValue, value to set interface to
/*        usb_ep0_rx_buffer[4] == wIndex, interface to set.
/* Returns: If a valid request, we send a 0 len packet to host as a reply.
/*
/* Summary: Set_Interface request handler.  Configure desired interface to use a specified alt. setting.
/*          Only valid when configured.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
void usb_Set_Interface() {
   int interface;

   debug(debug_txb,"SI ");

   if (USB_Curr_Config) { //if configured state
      interface=usb_ep0_rx_buffer[4];
      USB_Interface[interface]=usb_ep0_rx_buffer[2];
      usb_put_packet(0,usb_ep0_rx_buffer,0,DATA1); //send 0len packet
   }
   else { //not configured
      usb_wrongstate();
   }
}

////////////////////////////////////////////////////////////////////////////
///
/// The following functions retrieve data from constant arrays.  This may
/// look un-optimized, but remember that you can't create a pointer to
/// a constant array.
///
///////////////////////////////////////////////////////////////////////////

/**************************************************************
/* get_next_string_character()
/*
/* Returns: next character from string, or 0xFF when no more characters to pull.
/*
/* Summary: string_x are constant arrays that hold the string descriptors.  Since it's a constant
/*          array we cant create a pointer to it, therefore we have to do it one character at a time like this.
/*          string holds the string we are working on, String_ptr holds our current position on the string, and
/*          and the constant STRINGx has the length of the string.  Used in response to a Get_Descriptor request.
/*
/* Part of usb_isr_tok_setup_dne()
/***************************************************************/
#inline
int get_next_string_character() {
   int ret;

   switch (string) {
   #ifdef USB_STRING_0_LEN
      case 0: ret=USB_STRING_0[String_ptr++]; if (String_ptr>=USB_STRING_0_LEN) {String_ptr=0xFF;} break;
   #else
      #error You must be able to handle string 0.  See the example usb_desc.h for a U.S.A. definition
   #endif

   #ifdef USB_STRING_1_LEN
      case 1: ret=USB_STRING_1[String_ptr++]; if (String_ptr>=USB_STRING_1_LEN) {String_ptr=0xFF;} break;
   #endif

   #ifdef USB_STRING_2_LEN
      case 2: ret=USB_STRING_2[String_ptr++]; if (String_ptr>=USB_STRING_2_LEN) {String_ptr=0xFF;} break;
   #endif

   #ifdef USB_STRING_3_LEN
      case 3: ret=USB_STRING_3[String_ptr++]; if (String_ptr>=USB_STRING_3_LEN) {String_ptr=0xFF;} break;
   #endif

   #ifdef USB_STRING_4_LEN
      case 4: ret=USB_STRING_4[String_ptr++]; if (String_ptr>=USB_STRING_4_LEN) {String_ptr=0xFF;} break;
   #endif

   #ifdef USB_STRING_5_LEN
      case 5: ret=USB_STRING_5[String_ptr++]; if (String_ptr>=USB_STRING_5_LEN) {String_ptr=0xFF;} break;
   #endif

   #ifdef USB_STRING_6_LEN
      case 6: ret=USB_STRING_6[String_ptr++]; if (String_ptr>=USB_STRING_6_LEN) {String_ptr=0xFF;} break;
   #endif

   #ifdef USB_STRING_7_LEN
      case 7: ret=USB_STRING_7[String_ptr++]; if (String_ptr>=USB_STRING_7_LEN) {String_ptr=0xFF;} break;
   #endif

   #ifdef USB_STRING_8_LEN
      case 8: ret=USB_STRING_8[String_ptr++]; if (String_ptr>=USB_STRING_8_LEN) {String_ptr=0xFF;} break;
   #endif

   #ifdef USB_STRING_9_LEN
      case 9: ret=USB_STRING_9[String_ptr++]; if (String_ptr>=USB_STRING_9_LEN) {String_ptr=0xFF;} break;
   #endif

      default: break;
   }
   return(ret);
}

/****************************************************************************
/* usb_copy_string_seg_to_ep()
/*
/* Input: endpoint - endpoint to string descriptor to.  (Should always be 0, but just in case)
/*        tgl - Toggle the DATA0/1 PID, or use a DATA0 or a DATA1
/*
/* Summary:  Sends out 8 byte data packets that contain a string until all characters of
/* that string had been sent.  If a string is greater than 8 bytes it only sends
/* out 8 at a time, the next 8 will be sent on the next IN token.
/* Response to a Get_Descriptor request.
/*
/* Part of usb_isr_tok_setup_dne()
/*****************************************************************************/
#inline
void usb_copy_string_seg_to_ep(int endpoint, PID_TOGGLE tgl) {
   int i=0;

   while ((String_ptr!=0xFF)&&(i<USB_MAX_EP0_PACKET_LENGTH)&&(host_max_length-->0))
   {
      usb_ep0_rx_buffer[i++]=get_next_string_character();
   }


   if ((String_ptr==0xFF)&&(i==USB_MAX_EP0_PACKET_LENGTH)) {
      USB_dev_req = SEND_0LEN_TGL;
   }
   else if ((host_max_length == 0xFF)||(String_ptr==0xFF)) {
      USB_dev_req = NONE;
   }

   usb_put_packet(endpoint,usb_ep0_rx_buffer,i,tgl);
}


/****************************************************************************
/* usb_copy_config_seg_to_ep()
/*
/* Input: endpoint - endpoint to string descriptor to.  (Should always be 0, but just in case)
/*        tgl - Toggle the DATA0/1 PID, or use a DATA0 or a DATA1
/*
/* Summary: Sends out 8 byte data packets that contain the config descriptor until all
/* bytes of that descriptor had been sent.  If a string is greater than 8 bytes it
/* only sends out 8 at a time, the next 8 will be sent on the next IN token.
/* Response to a Get_Descriptor request.
/*
/* Part of usb_isr_tok_setup_dne()
*****************************************************************************/
#inline
void usb_copy_config_seg_to_ep(int endpoint, PID_TOGGLE tgl) {
   int i=0;

   while ((String_ptr<String_end)&&(i<USB_MAX_EP0_PACKET_LENGTH)&&(host_max_length-->0))
   {
      usb_ep0_rx_buffer[i++]=USB_CONFIG_DESC[String_ptr++];
   }

   if (String_ptr==String_end) {
      if ((i==USB_MAX_EP0_PACKET_LENGTH)&&(host_max_length != 0xFF)) {
         USB_dev_req = SEND_0LEN_TGL;
      }
      else {
         USB_dev_req = NONE;
      }
   }

   usb_put_packet(endpoint,usb_ep0_rx_buffer,i,tgl);
}

/****************************************************************************
/* usb_copy_device_seg_to_ep()
/*
/* Summary: Sends out 8 byte data packets that contain the device descriptor until all
/* bytes of that descriptor had been sent.  If a string is greater than 8 bytes it
/* only sends out 8 at a time, the next 8 will be sent on the next IN token.
/* Response to a Get_Descriptor request.
/*
/* Part of usb_isr_tok_setup_dne()
/*****************************************************************************/
#inline
void usb_copy_device_seg_to_ep(int endpoint, PID_TOGGLE tgl) {
   int i=0;

   while ((i<USB_MAX_EP0_PACKET_LENGTH)&&(host_max_length-->0)&&(String_ptr<USB_DEVICE_DESC_LEN))
   {
      usb_ep0_rx_buffer[i++]=USB_DEVICE_DESC[String_ptr++];
   }

   if (String_ptr==USB_DEVICE_DESC_LEN) {
      if ((i==USB_MAX_EP0_PACKET_LENGTH)&&(host_max_length != 0xFF)) {
         USB_dev_req = SEND_0LEN_TGL;
      }
      else {
         USB_dev_req = NONE;
      }
   }

   usb_put_packet(endpoint,usb_ep0_rx_buffer,i,tgl);
}

/****************************************************************************
/* usb_copy_hid_seg_to_ep()
/*
/* Summary: Sends out 8 byte data packets that contain the HID report descriptor until all
/* bytes of that descriptor had been sent.  If a string is greater than 8 bytes it
/* only sends out 8 at a time, the next 8 will be sent on the next IN token.
/* Response to a HID Get_Report request.
/*
/* Only compiled when using a HID_DEVICE.
/*
/* Part of usb_isr_tok_setup_dne()
/*****************************************************************************/
#IF USB_HID_DEVICE
#inline
void usb_copy_hid_seg_to_ep(int endpoint, PID_TOGGLE tgl) {
   int i=0;

   while ((String_ptr<USB_HID_DESC_LEN)&&(i<USB_MAX_EP0_PACKET_LENGTH)&&(host_max_length-->0))
   {
      usb_ep0_rx_buffer[i++]=USB_HID_DESC[String_ptr++];
   }

   if (String_ptr==USB_HID_DESC_LEN) {
      if (i==USB_MAX_EP0_PACKET_LENGTH) {
         USB_dev_req = SEND_0LEN_TGL;
      }
      else {
         USB_dev_req = NONE;
      }
   }


   usb_put_packet(endpoint,usb_ep0_rx_buffer,i,tgl);
}
#ENDIF

/// END USB Token, standard and HID request handler (part of ISR)

#ENDIF
