// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMcS7V5q3MDkWkZ4pVCXVNkodZQpfdjKM',
    appId: '1:883289097713:web:a64ae799e9ebe4bdb63050',
    messagingSenderId: '883289097713',
    projectId: 'monitoramento--qualidade-do-ar',
    authDomain: 'monitoramento--qualidade-do-ar.firebaseapp.com',
    databaseURL: 'https://monitoramento--qualidade-do-ar-default-rtdb.firebaseio.com',
    storageBucket: 'monitoramento--qualidade-do-ar.firebasestorage.app',
    measurementId: 'G-XWN2S8RMZK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuKfrfcX0K2V5jgBGSpCQZvSk7nJ5Dits',
    appId: '1:883289097713:android:e80737eea18093dab63050',
    messagingSenderId: '883289097713',
    projectId: 'monitoramento--qualidade-do-ar',
    databaseURL: 'https://monitoramento--qualidade-do-ar-default-rtdb.firebaseio.com',
    storageBucket: 'monitoramento--qualidade-do-ar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACvyIX9JcdzN2BtZc3E_q8x9vdVJJ_s3c',
    appId: '1:883289097713:ios:2fdc27682cc5a2adb63050',
    messagingSenderId: '883289097713',
    projectId: 'monitoramento--qualidade-do-ar',
    databaseURL: 'https://monitoramento--qualidade-do-ar-default-rtdb.firebaseio.com',
    storageBucket: 'monitoramento--qualidade-do-ar.firebasestorage.app',
    iosBundleId: 'com.example.monitoramentoAr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACvyIX9JcdzN2BtZc3E_q8x9vdVJJ_s3c',
    appId: '1:883289097713:ios:2fdc27682cc5a2adb63050',
    messagingSenderId: '883289097713',
    projectId: 'monitoramento--qualidade-do-ar',
    databaseURL: 'https://monitoramento--qualidade-do-ar-default-rtdb.firebaseio.com',
    storageBucket: 'monitoramento--qualidade-do-ar.firebasestorage.app',
    iosBundleId: 'com.example.monitoramentoAr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMcS7V5q3MDkWkZ4pVCXVNkodZQpfdjKM',
    appId: '1:883289097713:web:a999fb065a5e144db63050',
    messagingSenderId: '883289097713',
    projectId: 'monitoramento--qualidade-do-ar',
    authDomain: 'monitoramento--qualidade-do-ar.firebaseapp.com',
    databaseURL: 'https://monitoramento--qualidade-do-ar-default-rtdb.firebaseio.com',
    storageBucket: 'monitoramento--qualidade-do-ar.firebasestorage.app',
    measurementId: 'G-LDFMFBJ0HP',
  );
}
